language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
    deploy:
      - provider: s3
        ⋮ 
      - provider: codedeploy
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY"
        bucket: "my-app-henry"
        key: latest/MyApp.zip
        application: my-app
        deployment_group: my-app-group
        on:
          branch: master
