language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  # - npm test
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY"
    application: my-app
    deployment_group: my-app-group
    region: ap-southeast-2
    on:
     branch: master

