version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: / 
    pattern: "**"
    owner: ec2-user
hooks:
  AfterInstall:
    - location: /home/ec2-user/app/scripts/afterinstall.sh
